test:
	g++ -o test.o test.cpp -I/usr/local/include -I/opt/local/include -I/usr/include -I/usr/include/c++/4.2.1 -I//usr/include/c++/4.2.1/backward -I/usr/include/sys -I/opt/local/lib/gcc48/gcc/x86_64-apple-darwin13/4.8.2/include -ferror-limit=2000
